<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.8" tiledversion="1.8.2" name="TilesetShop" tilewidth="32" tileheight="32" tilecount="128" columns="8">
 <image source="../TiledsetTexture/TilesetShop.png" width="256" height="512"/>
 <tile id="0" type="Background"/>
 <tile id="1" type="Background"/>
 <tile id="2" type="Background"/>
 <tile id="3" type="Background"/>
 <tile id="4" type="Background"/>
 <tile id="5" type="Background"/>
 <tile id="6" type="Background"/>
 <tile id="7" type="Background"/>
 <tile id="8" type="Background"/>
 <tile id="9" type="Background"/>
 <tile id="10" type="Background"/>
 <tile id="11" type="Background"/>
 <tile id="12" type="Background"/>
 <tile id="13" type="Background"/>
 <tile id="14" type="Background"/>
 <tile id="15" type="Background"/>
 <tile id="16" type="Background"/>
 <tile id="17" type="Background"/>
 <tile id="18" type="Background"/>
 <tile id="19" type="Background"/>
 <tile id="20" type="Background"/>
 <tile id="21" type="Background"/>
 <tile id="22" type="Background"/>
 <tile id="23" type="Background"/>
 <tile id="24" type="Background"/>
 <tile id="25" type="Background"/>
 <tile id="26" type="Background"/>
 <tile id="27" type="Background"/>
 <tile id="28" type="Background"/>
 <tile id="29" type="Background"/>
 <tile id="30" type="Background"/>
 <tile id="31" type="Background"/>
 <tile id="32" type="Background"/>
 <tile id="33" type="Background"/>
 <tile id="34" type="Background"/>
 <tile id="35" type="Background"/>
 <tile id="36" type="Background"/>
 <tile id="37" type="Background"/>
 <tile id="38" type="Background"/>
 <tile id="39" type="Background"/>
 <tile id="40" type="Background"/>
 <tile id="41" type="Background"/>
 <tile id="42" type="Background"/>
 <tile id="43" type="Background"/>
 <tile id="44" type="Background"/>
 <tile id="45" type="Background"/>
 <tile id="46" type="Background"/>
 <tile id="47" type="Background"/>
 <tile id="48" type="Background"/>
 <tile id="49" type="Background"/>
 <tile id="50" type="Background"/>
 <tile id="51" type="Background"/>
 <tile id="52" type="Background"/>
 <tile id="53" type="Background"/>
 <tile id="54" type="Background"/>
 <tile id="55" type="Background"/>
 <tile id="56" type="Background"/>
 <tile id="57" type="Background"/>
 <tile id="58" type="Background"/>
 <tile id="59" type="Background"/>
 <tile id="60" type="Background"/>
 <tile id="61" type="Background"/>
 <tile id="62" type="Background"/>
 <tile id="63" type="Background"/>
 <tile id="64" type="Background"/>
 <tile id="65" type="Background"/>
 <tile id="66" type="Background"/>
 <tile id="67" type="Background"/>
 <tile id="68" type="Background"/>
 <tile id="69" type="Background"/>
 <tile id="70" type="Background"/>
 <tile id="71" type="Background"/>
 <tile id="72" type="Background"/>
 <tile id="73" type="Background"/>
 <tile id="74" type="Background"/>
 <tile id="75" type="Background"/>
 <tile id="76" type="Background"/>
 <tile id="77" type="Background"/>
 <tile id="78" type="Background"/>
 <tile id="79" type="Background"/>
 <tile id="80" type="Background"/>
 <tile id="81" type="Background"/>
 <tile id="82" type="Background"/>
 <tile id="83" type="Background"/>
 <tile id="84" type="Background"/>
 <tile id="85" type="Background"/>
 <tile id="86" type="Background"/>
 <tile id="87" type="Background"/>
 <tile id="88" type="Background"/>
 <tile id="89" type="Background"/>
 <tile id="90" type="Background"/>
 <tile id="91" type="Background"/>
 <tile id="92" type="Background"/>
 <tile id="93" type="Background"/>
 <tile id="94" type="Background"/>
 <tile id="95" type="Background"/>
 <tile id="96" type="Background"/>
 <tile id="97" type="Background"/>
 <tile id="98" type="Background"/>
 <tile id="99" type="Background"/>
 <tile id="100" type="Background"/>
 <tile id="101" type="Background"/>
 <tile id="102" type="Background"/>
 <tile id="103" type="Background"/>
 <tile id="104" type="Background"/>
 <tile id="105" type="Background"/>
 <tile id="106" type="Background"/>
 <tile id="107" type="Background"/>
 <tile id="108" type="Background"/>
 <tile id="109" type="Background"/>
 <tile id="110" type="Background"/>
 <tile id="111" type="Background"/>
 <tile id="112" type="Background"/>
 <tile id="113" type="Background"/>
 <tile id="114" type="Background"/>
 <tile id="115" type="Background"/>
 <tile id="116" type="Background"/>
 <tile id="117" type="Background"/>
 <tile id="118" type="Background"/>
 <tile id="119" type="Background"/>
 <tile id="120" type="Background"/>
 <tile id="121" type="Background"/>
 <tile id="122" type="Background"/>
 <tile id="123" type="Background"/>
 <tile id="124" type="Background"/>
 <tile id="125" type="Background"/>
 <tile id="126" type="Background"/>
 <tile id="127" type="Background"/>
</tileset>
